"""Audit reproducible pipeline coverage for manuscript-facing reports.

The audit scans report-like Markdown documents and classifies whether each is
covered by the current publication pipeline, reusable as an existing output, or
exploratory/needs review. It is deliberately conservative: unknown reports are
not promoted to manuscript support without an explicit mapping.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import pandas as pd


MANUSCRIPT_ROOT = Path("outputs/manuscript")
OUT_CSV = MANUSCRIPT_ROOT / "metrics" / "manuscript_pipeline_coverage.csv"
OUT_REPORT = MANUSCRIPT_ROOT / "reports" / "manuscript_pipeline_coverage_report.md"


@dataclass(frozen=True)
class KnownReport:
    """Known manuscript-supporting report mapping."""

    report_name: str
    manuscript_items: str
    generating_script: str
    included_in_publication_pipeline: bool
    expected_source_path: str
    notes: str


def known_report_mappings() -> dict[str, KnownReport]:
    """Return exact known manuscript-supporting report mappings by filename."""
    reports = [
        KnownReport(
            "pnab_parallel_antiparallel_audit_report.md",
            "1",
            "scripts/audit_pnab_parallel_antiparallel_models.py",
            True,
            "outputs/reports/pnab_parallel_antiparallel_audit_report.md",
            "pNAB/scaffold compatibility audit; parallel remains insufficient_data.",
        ),
        KnownReport(
            "guarded_full_chain_prototype_report.md",
            "4,5,6",
            "scripts/build_guarded_full_chain_prototype.py",
            True,
            "outputs/reports/guarded_full_chain_prototype_report.md",
            "Physical/chemical-sense guard source for the omega-clean candidate family.",
        ),
        KnownReport(
            "omega_clean_rise_compression_report.md",
            "3,5,8",
            "scripts/run_omega_clean_rise_compression_scan.py",
            True,
            "outputs/reports/omega_clean_rise_compression_report.md",
            "Rise-compression scan supporting C/D plateau and D over-compression guardrail.",
        ),
        KnownReport(
            "omega_clean_torsion_boundary_report.md",
            "7",
            "scripts/run_omega_clean_torsion_boundary_scan.py",
            True,
            "outputs/reports/omega_clean_torsion_boundary_report.md",
            "Measured local torsion-boundary range around the surviving family.",
        ),
        KnownReport(
            "item6_candidate_filter_funnel_report.md",
            "4,6",
            "scripts/report_item6_candidate_filter_funnel.py",
            True,
            "outputs/reports/item6_candidate_filter_funnel_report.md",
            "Candidate-filter funnel report.",
        ),
        KnownReport(
            "manuscript_reproducibility_summary.md",
            "1,2,3,4,5,6,7,8",
            "scripts/run_manuscript_reproducibility_pipeline.py",
            True,
            "outputs/manuscript/reports/manuscript_reproducibility_summary.md",
            "Publication-track summary generated by the manuscript pipeline.",
        ),
        KnownReport(
            "manuscript_pipeline_coverage_report.md",
            "1,2,3,4,5,6,7,8",
            "scripts/audit_manuscript_pipeline_coverage.py",
            True,
            "outputs/manuscript/reports/manuscript_pipeline_coverage_report.md",
            "Coverage audit for manuscript-supporting analysis documents.",
        ),
    ]
    return {report.report_name: report for report in reports}


def known_script_mappings() -> dict[str, str]:
    """Return known manuscript-supporting script mappings."""
    return {report.generating_script: report.report_name for report in known_report_mappings().values()}


def scan_report_paths(root: Path = Path(".")) -> list[Path]:
    """Scan report-like Markdown paths."""
    candidates: set[Path] = set()
    for base in [root / "outputs" / "reports", root / "outputs" / "manuscript" / "reports"]:
        if base.exists():
            candidates.update(path for path in base.glob("*.md") if path.is_file())
    candidates.update(path for path in root.glob("*.md") if path.is_file())
    return sorted(candidates, key=lambda path: str(path).lower())


def infer_generating_script(report_path: Path, mapping: KnownReport | None) -> str:
    """Infer generating script for a report."""
    if mapping is not None:
        return mapping.generating_script
    name = report_path.name
    stem = name.removesuffix("_report.md").removesuffix(".md")
    candidates = [
        Path("scripts") / f"{stem}.py",
        Path("scripts") / f"run_{stem}.py",
        Path("scripts") / f"analyze_{stem}.py",
        Path("scripts") / f"audit_{stem}.py",
        Path("scripts") / f"score_{stem}.py",
    ]
    for candidate in candidates:
        if candidate.exists():
            return str(candidate)
    return ""


def manuscript_copy_path(report_path: Path) -> Path:
    """Return expected manuscript copy path for a report."""
    return MANUSCRIPT_ROOT / "reports" / report_path.name


def classify_report_status(
    report_path: Path,
    mapping: KnownReport | None,
    generating_script: str,
    script_exists: bool,
    copied_to_manuscript: bool,
) -> str:
    """Classify report pipeline coverage status."""
    if mapping is not None and mapping.included_in_publication_pipeline and copied_to_manuscript and script_exists:
        return "reproducible_in_publication_pipeline"
    if mapping is not None and mapping.included_in_publication_pipeline and report_path.exists() and script_exists:
        return "reusable_existing_output"
    if mapping is not None and not report_path.exists():
        return "missing_expected_report"
    if generating_script and script_exists:
        return "script_exists_not_in_publication_pipeline"
    if "outputs" in report_path.parts:
        return "exploratory_only"
    if report_path.name in {"MANUSCRIPT_CLAIM_MAP.md", "REPRODUCIBILITY.md", "PUBLICATION_TRACK.md"}:
        return "reproducible_in_publication_pipeline"
    if not generating_script:
        return "orphan_report_no_script"
    return "needs_review"


def report_row(report_path: Path, root: Path = Path(".")) -> dict[str, object]:
    """Return one coverage row for a report."""
    mapping = known_report_mappings().get(report_path.name)
    generating_script = infer_generating_script(report_path, mapping)
    script_exists = bool(generating_script) and (root / generating_script).exists()
    copied_to_manuscript = report_path.parent == root / MANUSCRIPT_ROOT / "reports" or (root / manuscript_copy_path(report_path)).exists()
    status = classify_report_status(report_path, mapping, generating_script, script_exists, copied_to_manuscript)
    if mapping is not None:
        items = mapping.manuscript_items
        included = mapping.included_in_publication_pipeline
        expected = mapping.expected_source_path
        notes = mapping.notes
    else:
        items = infer_items_from_name(report_path.name)
        included = False
        expected = ""
        notes = "Exploratory or unmapped report; not treated as manuscript-supporting without review."
    return {
        "report_path": str(report_path),
        "report_name": report_path.name,
        "inferred_manuscript_items": items,
        "inferred_generating_script": generating_script,
        "generating_script_exists": script_exists,
        "included_in_publication_pipeline": included,
        "copied_into_outputs_manuscript": copied_to_manuscript,
        "expected_source_path": expected,
        "status": status,
        "notes": notes,
    }


def infer_items_from_name(name: str) -> str:
    """Conservative item inference from report filename."""
    value = name.lower()
    items: list[str] = []
    if "pnab" in value or "parallel_antiparallel" in value:
        items.append("1")
    if "rise" in value or "compression" in value:
        items.extend(["3", "8"])
    if "item6" in value or "funnel" in value:
        items.append("6")
    if "torsion_boundary" in value:
        items.append("7")
    return ",".join(dict.fromkeys(items))


def add_missing_expected_rows(df: pd.DataFrame, root: Path = Path(".")) -> pd.DataFrame:
    """Append missing rows for known expected reports absent from scan."""
    existing_names = set(df["report_name"].tolist()) if not df.empty else set()
    rows = []
    for report in known_report_mappings().values():
        if report.report_name in existing_names:
            continue
        expected = root / report.expected_source_path
        if expected.exists():
            continue
        if report.report_name == OUT_REPORT.name:
            rows.append(
                {
                    "report_path": report.expected_source_path,
                    "report_name": report.report_name,
                    "inferred_manuscript_items": report.manuscript_items,
                    "inferred_generating_script": report.generating_script,
                    "generating_script_exists": (root / report.generating_script).exists(),
                    "included_in_publication_pipeline": report.included_in_publication_pipeline,
                    "copied_into_outputs_manuscript": True,
                    "expected_source_path": report.expected_source_path,
                    "status": "reproducible_in_publication_pipeline",
                    "notes": report.notes,
                }
            )
            continue
        rows.append(
            {
                "report_path": report.expected_source_path,
                "report_name": report.report_name,
                "inferred_manuscript_items": report.manuscript_items,
                "inferred_generating_script": report.generating_script,
                "generating_script_exists": (root / report.generating_script).exists(),
                "included_in_publication_pipeline": report.included_in_publication_pipeline,
                "copied_into_outputs_manuscript": False,
                "expected_source_path": report.expected_source_path,
                "status": "missing_expected_report",
                "notes": report.notes,
            }
        )
    if rows:
        return pd.concat([df, pd.DataFrame(rows)], ignore_index=True)
    return df


def build_coverage(root: Path = Path(".")) -> pd.DataFrame:
    """Build coverage dataframe."""
    rows = [report_row(path, root) for path in scan_report_paths(root)]
    df = pd.DataFrame(rows)
    df = add_missing_expected_rows(df, root)
    if df.empty:
        return pd.DataFrame(
            columns=[
                "report_path",
                "report_name",
                "inferred_manuscript_items",
                "inferred_generating_script",
                "generating_script_exists",
                "included_in_publication_pipeline",
                "copied_into_outputs_manuscript",
                "expected_source_path",
                "status",
                "notes",
            ]
        )
    return df.sort_values(["included_in_publication_pipeline", "status", "report_name"], ascending=[False, True, True]).reset_index(drop=True)


def markdown_table(df: pd.DataFrame, columns: list[str], limit: int | None = None) -> str:
    """Return markdown table."""
    if df.empty:
        return "_None._"
    subset = df[columns].head(limit) if limit else df[columns]
    lines = ["| " + " | ".join(columns) + " |", "| " + " | ".join("---" for _ in columns) + " |"]
    for _, row in subset.iterrows():
        lines.append("| " + " | ".join(str(row.get(column, "")) for column in columns) + " |")
    return "\n".join(lines)


def build_report(df: pd.DataFrame) -> str:
    """Build coverage report text."""
    status_counts = df.groupby("status").size().reset_index(name="count").sort_values("status") if not df.empty else pd.DataFrame()
    covered = df[df["status"] == "reproducible_in_publication_pipeline"]
    reused = df[df["status"] == "reusable_existing_output"]
    needs = df[df["status"].isin(["needs_review", "orphan_report_no_script", "missing_expected_report", "script_exists_not_in_publication_pipeline"])]
    cols = ["report_name", "inferred_manuscript_items", "inferred_generating_script", "status"]
    return f"""# Manuscript Pipeline Coverage Audit

This pipeline coverage audit checks manuscript-supporting analysis documents and asks whether each has a reproducible path through the publication pipeline. It is conservative: exploratory reports remain exploratory unless explicitly mapped.

## Status Counts

{markdown_table(status_counts, ["status", "count"]) if not status_counts.empty else "_None._"}

## Reports Fully Covered By Publication Pipeline

{markdown_table(covered, cols)}

## Reports Using Reused Existing Output

{markdown_table(reused, cols)}

## Reports Needing Review

{markdown_table(needs, cols, limit=40)}

## Notes

- `reproducible_in_publication_pipeline` means the report is mapped to a manuscript item, has an existing generating script, and is present or copied in `outputs/manuscript/reports/`.
- `reusable_existing_output` means a known manuscript-supporting source output exists and can be reused, but the manuscript copy may not yet be present at audit time.
- `needs_review` means the report may be relevant but is not explicitly mapped into the publication track.
- `exploratory_only` reports are not manuscript-supporting analysis documents unless promoted later.
"""


def run(out_csv: Path = OUT_CSV, out_report: Path = OUT_REPORT, root: Path = Path(".")) -> pd.DataFrame:
    """Run coverage audit and write outputs."""
    df = build_coverage(root)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    out_report.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_csv, index=False)
    out_report.write_text(build_report(df), encoding="utf-8")
    return df


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Audit manuscript pipeline coverage for report documents.")
    parser.add_argument("--out-csv", type=Path, default=OUT_CSV)
    parser.add_argument("--out-report", type=Path, default=OUT_REPORT)
    args = parser.parse_args()
    df = run(args.out_csv, args.out_report)
    print(f"Coverage rows: {len(df)}")
    if not df.empty:
        print(df.groupby("status").size().sort_index().to_string())
    print(f"Report: {args.out_report}")


if __name__ == "__main__":
    main()
