"""Roll up ideal Hexaflex atom-class C/D diagnostics across variants."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.analyze_ideal_hexaflex_atom_class_cd import canonical_pair_class


DEFAULT_VARIANTS = [
    "full",
    "no_h",
    "backbone_only",
    "peptide_plane_only",
    "no_side_chain",
    "backbone_plus_carboxylate",
    "peptide_plane_plus_carboxylate",
    "side_chain_only",
    "carboxylate_only",
]
FOCUS_PAIRS = [
    ("peptide_plane", "peptide_plane"),
    ("peptide_plane", "carboxylate"),
    ("backbone", "backbone"),
    ("backbone", "carboxylate"),
    ("side_chain_non_carboxylate", "side_chain_non_carboxylate"),
    ("carboxylate", "carboxylate"),
    ("carbon", "oxygen"),
    ("carbon", "carbon"),
    ("nitrogen", "oxygen"),
    ("oxygen", "oxygen"),
]
FOCUS_GEOMETRIES = ["all_cross_strand", "all_same_strand", "adjacent_strand_same_register"]


def top_row(df: pd.DataFrame, column: str) -> pd.Series:
    """Return row with max numeric value."""
    values = pd.to_numeric(df[column], errors="coerce").fillna(float("-inf"))
    return df.loc[values.idxmax()]


def pair_value(df: pd.DataFrame, class_a: str, class_b: str, geometry: str, column: str) -> float:
    """Return a focused atom-pair/geometry metric value."""
    a, b = canonical_pair_class(class_a, class_b)
    subset = df[
        (df["atom_class_1"] == a)
        & (df["atom_class_2"] == b)
        & (df["geometry_family"] == geometry)
    ]
    if subset.empty or column not in df.columns:
        return 0.0
    value = pd.to_numeric(subset.iloc[0][column], errors="coerce")
    return float(value) if pd.notna(value) else 0.0


def summarize_file(summary_path: Path, variant: str) -> dict[str, object]:
    """Summarize one atom-class C/D summary CSV."""
    df = pd.read_csv(summary_path)
    top_c_count = top_row(df, "C_pair_count")
    top_d_count = top_row(df, "D_pair_count")
    top_c_profile = top_row(df.fillna({"C_profile_max_intensity": float("-inf")}), "C_profile_max_intensity")
    top_d_profile = top_row(df.fillna({"D_profile_max_intensity": float("-inf")}), "D_profile_max_intensity")
    row: dict[str, object] = {
        "variant": variant,
        "model_id": str(df["model_id"].dropna().iloc[0]) if "model_id" in df and not df["model_id"].dropna().empty else summary_path.stem,
        "summary_path": str(summary_path),
        "top_C_pair_count_label": label(top_c_count),
        "top_C_pair_count": float(top_c_count.C_pair_count),
        "top_D_pair_count_label": label(top_d_count),
        "top_D_pair_count": float(top_d_count.D_pair_count),
        "top_C_profile_label": label(top_c_profile),
        "top_C_profile_peak_d_A": float(top_c_profile.C_profile_peak_d_A),
        "top_C_profile_max_intensity": float(top_c_profile.C_profile_max_intensity),
        "top_D_profile_label": label(top_d_profile),
        "top_D_profile_peak_d_A": float(top_d_profile.D_profile_peak_d_A),
        "top_D_profile_max_intensity": float(top_d_profile.D_profile_max_intensity),
    }
    for class_a, class_b in FOCUS_PAIRS:
        pair_name = f"{class_a}__{class_b}"
        for geometry in FOCUS_GEOMETRIES:
            prefix = f"{pair_name}__{geometry}"
            row[f"{prefix}__C_pair_count"] = pair_value(df, class_a, class_b, geometry, "C_pair_count")
            row[f"{prefix}__D_pair_count"] = pair_value(df, class_a, class_b, geometry, "D_pair_count")
    return row


def label(row: pd.Series) -> str:
    """Format one atom-class/geometry label."""
    return f"{row.atom_class_1} x {row.atom_class_2} / {row.geometry_family}"


def variant_from_manifest_model_id(model_id: str) -> str:
    """Infer variant from model ID generated by the variant builder."""
    prefix = "ideal_hexaflex_"
    suffix = "_pair_family_cd"
    if model_id.startswith(prefix) and model_id.endswith(suffix):
        return model_id[len(prefix) : -len(suffix)]
    return model_id


def load_variant_model_ids(manifest_path: Path | None) -> list[tuple[str, str]]:
    """Return requested variant/model-id pairs."""
    if manifest_path is None or not manifest_path.exists():
        return [(variant, f"ideal_hexaflex_{variant}_pair_family_cd") for variant in DEFAULT_VARIANTS]
    manifest = pd.read_csv(manifest_path)
    rows = []
    for row in manifest.itertuples(index=False):
        if hasattr(row, "written") and str(row.written).lower() not in {"true", "1"}:
            continue
        model_id = str(row.model_id)
        rows.append((str(row.variant), model_id))
    return rows


def save_heatmap(rollup: pd.DataFrame, path_base: Path) -> None:
    """Plot focused C/D atom-class count heatmap."""
    focus_columns = [
        "peptide_plane__peptide_plane__all_cross_strand__C_pair_count",
        "peptide_plane__peptide_plane__all_cross_strand__D_pair_count",
        "backbone__backbone__all_cross_strand__C_pair_count",
        "backbone__backbone__all_cross_strand__D_pair_count",
        "backbone__carboxylate__all_cross_strand__C_pair_count",
        "backbone__carboxylate__all_cross_strand__D_pair_count",
        "side_chain_non_carboxylate__side_chain_non_carboxylate__all_cross_strand__C_pair_count",
        "side_chain_non_carboxylate__side_chain_non_carboxylate__all_cross_strand__D_pair_count",
    ]
    columns = [column for column in focus_columns if column in rollup.columns]
    if not columns:
        return
    matrix = rollup.set_index("variant")[columns].astype(float)
    display = np.log10(matrix + 1.0)
    fig, ax = plt.subplots(figsize=(11, 5.5))
    image = ax.imshow(display.values, aspect="auto", cmap="viridis")
    ax.set_yticks(range(len(display.index)), display.index)
    ax.set_xticks(range(len(display.columns)), [short_label(col) for col in display.columns], rotation=45, ha="right")
    ax.set_title("Ideal Hexaflex atom-class C/D pair-count heatmap (log10 count+1)")
    fig.colorbar(image, ax=ax, label="log10(pair count + 1)")
    fig.tight_layout()
    fig.savefig(path_base.with_suffix(".png"), dpi=180)
    fig.savefig(path_base.with_suffix(".svg"))
    plt.close(fig)


def short_label(column: str) -> str:
    """Shorten heatmap column labels."""
    return (
        column.replace("__all_cross_strand__", "\n")
        .replace("__C_pair_count", " C")
        .replace("__D_pair_count", " D")
        .replace("peptide_plane", "pep")
        .replace("carboxylate", "carb")
        .replace("side_chain_non_carboxylate", "side-noncarb")
    )


def markdown_table(df: pd.DataFrame, columns: list[str]) -> str:
    """Render selected columns as a markdown table."""
    columns = [column for column in columns if column in df.columns]
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join("---" for _ in columns) + " |",
    ]
    for record in df[columns].itertuples(index=False):
        values = []
        for value in record:
            if isinstance(value, float):
                values.append(f"{value:.4g}")
            else:
                values.append(str(value))
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def write_report(rollup: pd.DataFrame, path: Path) -> None:
    """Write rollup markdown interpretation."""
    if rollup.empty:
        path.write_text("# Ideal Hexaflex Atom-Class C/D Rollup\n\nNo summaries were found.\n", encoding="utf-8")
        return
    table = markdown_table(
        rollup,
        [
            "variant",
            "top_C_pair_count_label",
            "top_C_pair_count",
            "top_D_pair_count_label",
            "top_D_pair_count",
            "top_C_profile_label",
            "top_C_profile_peak_d_A",
            "top_D_profile_label",
            "top_D_profile_peak_d_A",
        ],
    )
    side_rows = rollup[rollup["variant"].isin(["full", "no_h", "side_chain_only"])]
    carb_rows = rollup[rollup["variant"].str.contains("carboxylate", regex=False)]
    side_top = "; ".join(f"{row.variant}: {row.top_C_pair_count_label}" for row in side_rows.itertuples())
    carb_top = "; ".join(f"{row.variant}: {row.top_D_pair_count_label}" for row in carb_rows.itertuples())
    text = f"""# Ideal Hexaflex Atom-Class C/D Rollup

This rollup summarizes atom-class and geometry-family C/D diagnostics for ideal Hexaflex selection variants. Atom classes are overlapping diagnostic labels, not disjoint ablation groups.

## Per-Variant Top Atom-Class Families

{table}

## Cautious Interpretation

- Atom-class pairs that best recover C near 5.6 A should be read from the C profile peak and C pair-count winners above, with special attention to peptide-plane/backbone cross-strand rows in the CSV.
- Atom-class pairs that preserve or tune D near 7.2-7.3 A are visible in the D profile columns and carboxylate-containing variants.
- Full/no-H/side-chain-only high-peak behavior: {side_top}
- Carboxylate-containing D behavior: {carb_top}
- Whether carboxylate helps D mainly through cross-strand contacts can be checked in the `backbone__carboxylate__all_cross_strand` and `peptide_plane__carboxylate__all_cross_strand` columns of the rollup CSV.
- Whether C recovery is peptide-plane-core, backbone-core, or carboxylate-assisted should be judged by comparing `peptide_plane x peptide_plane`, `backbone x backbone`, and carboxylate-cross rows across stripped and carboxylate-added variants.

## Outputs

- Rollup CSV: `outputs/metrics/ideal_hexaflex_atom_class_cd_rollup.csv`
- Heatmap PNG/SVG: `outputs/figures/ideal_hexaflex_atom_class_cd_C_D_heatmap.png` and `.svg`
"""
    path.write_text(text, encoding="utf-8")


def rollup(
    metrics_dir: Path,
    manifest_path: Path | None,
    out_metrics: Path,
    out_reports: Path,
    out_figures: Path,
) -> pd.DataFrame:
    """Create atom-class rollup outputs."""
    rows = []
    for variant, model_id in load_variant_model_ids(manifest_path):
        path = metrics_dir / f"{model_id}_atom_class_cd_summary.csv"
        if path.exists():
            rows.append(summarize_file(path, variant))
    df = pd.DataFrame(rows)
    out_metrics.mkdir(parents=True, exist_ok=True)
    out_reports.mkdir(parents=True, exist_ok=True)
    out_figures.mkdir(parents=True, exist_ok=True)
    csv_path = out_metrics / "ideal_hexaflex_atom_class_cd_rollup.csv"
    report_path = out_reports / "ideal_hexaflex_atom_class_cd_rollup_report.md"
    df.to_csv(csv_path, index=False)
    write_report(df, report_path)
    if not df.empty:
        save_heatmap(df, out_figures / "ideal_hexaflex_atom_class_cd_C_D_heatmap")
    return df


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metrics-dir", type=Path, default=Path("outputs/metrics"))
    parser.add_argument(
        "--variant-manifest",
        type=Path,
        default=Path("outputs/coordinates/ideal_hexaflex_variants/variant_manifest.csv"),
    )
    parser.add_argument("--out-metrics", type=Path, default=Path("outputs/metrics"))
    parser.add_argument("--out-reports", type=Path, default=Path("outputs/reports"))
    parser.add_argument("--out-figures", type=Path, default=Path("outputs/figures"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    df = rollup(args.metrics_dir, args.variant_manifest, args.out_metrics, args.out_reports, args.out_figures)
    print(f"Summarized {len(df)} atom-class diagnostic files")
    print(f"CSV: {args.out_metrics / 'ideal_hexaflex_atom_class_cd_rollup.csv'}")
    print(f"Report: {args.out_reports / 'ideal_hexaflex_atom_class_cd_rollup_report.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
